[colors.bright]
black = "#4d5960"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.normal]
black = "#4d5960"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.primary]
background = "#333c43"
foreground = "#d3c6aa"

[cursor]
style = "Block"
unfocused_hollow = true
vi_mode_style = "None"

[font.normal]
family = "OpenDyslexicM Nerd Font"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[terminal]
shell.program = "/opt/homebrew/bin/fish"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.8
startup_mode = "Maximized"
title = '''Melinal'''

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[window.position]
x = 0
y = 0
