[colors.bright]
# light soft
# black = "#5c6a72"
# blue = "#3a94c5"
# cyan = "#35a77c"
# green = "#8da101"
# magenta = "#df69ba"
# red = "#f85552"
# white = "#d8d3ba"
# yellow = "#dfa000"

# light dark
# black = "#4d5960"
# blue = "#7fbbb3"
# cyan = "#83c092"
# green = "#a7c080"
# magenta = "#d699b6"
# red = "#e67e80"
# white = "#d3c6aa"
# yellow = "#dbbc7f"

# medium dark
black = "#475258"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

# light hard
# black = "#5c6a72"
# red = "#f85552"
# green = "#8da101"
# yellow = "#dfa000"
# blue = "#3a94c5"
# magenta = "#df69ba"
# cyan = "#35a77c"
# white = "#e8e5d5"

[colors.normal]
# light soft
# black = "#5c6a72"
# blue = "#3a94c5"
# cyan = "#35a77c"
# green = "#8da101"
# magenta = "#df69ba"
# red = "#f85552"
# white = "#d8d3ba"
# yellow = "#dfa000"

# light dark
# black = "#4d5960"
# blue = "#7fbbb3"
# cyan = "#83c092"
# green = "#a7c080"
# magenta = "#d699b6"
# red = "#e67e80"
# white = "#d3c6aa"
# yellow = "#dbbc7f"

# medium dark
black = "#475258"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

# light hard
# black = "#5c6a72"
# red = "#f85552"
# green = "#8da101"
# yellow = "#dfa000"
# blue = "#3a94c5"
# magenta = "#df69ba"
# cyan = "#35a77c"
# white = "#e8e5d5"

[colors.primary]
# light soft
# background = "#f3ead3"
# foreground = "#5c6a72"

# light dark
# background = "#333c43"
# foreground = "#d3c6aa"

# medium dark
background = "#2d353b"
foreground = "#d3c6aa"

# light hard
# background = "#fffbef"
# foreground = "#5c6a72"

[cursor]
style = "Block"
unfocused_hollow = true
vi_mode_style = "None"

[font.normal]
family = "OpenDyslexicM Nerd Font"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[terminal]
shell.program = "/opt/homebrew/bin/fish"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.8
startup_mode = "Maximized"
title = '''Melinal'''

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[window.position]
x = 0
y = 0
